// Auto-generated by update-news.ts
export type AINewsItem = {
  title: string;
  link: string;
  pubDate: string;
  source: string;
};

export const aiNews: AINewsItem[] = [
  {
    "title": "Beyond single-model AI: How architectural design drives reliable multi-agent orchestration",
    "link": "https://venturebeat.com/ai/beyond-single-model-ai-how-architectural-design-drives-reliable-multi-agent-orchestration/",
    "pubDate": "Sat, 24 May 2025 22:35:00 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "OpenAI updates Operator to o3, making its $200 monthly ChatGPT Pro subscription more enticing",
    "link": "https://venturebeat.com/ai/openai-updates-operator-to-o3-making-its-200-monthly-chatgpt-subscription-more-enticing/",
    "pubDate": "Fri, 23 May 2025 21:51:51 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "The battle to AI-enable the web: NLweb and what enterprises need to know",
    "link": "https://venturebeat.com/ai/the-battle-to-ai-enable-the-web-nlweb-and-what-enterprises-need-to-know/",
    "pubDate": "Fri, 23 May 2025 21:05:53 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "The 3 biggest bombshells from this week’s AI extravaganza",
    "link": "https://venturebeat.com/ai/the-3-biggest-bombshells-from-this-weeks-ai-extravaganza/",
    "pubDate": "Fri, 23 May 2025 20:29:55 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "Watch how our Android XR glasses work with Gemini in the real world.",
    "link": "https://blog.google/products/android/android-xr-glasses-demo-io-2025/",
    "pubDate": "Fri, 23 May 2025 16:00:00 +0000",
    "source": "The Keyword"
  },
  {
    "title": "Why enterprise RAG systems fail: Google study introduces ‘sufficient context’ solution",
    "link": "https://venturebeat.com/ai/why-enterprise-rag-systems-fail-google-study-introduces-sufficient-context-solution/",
    "pubDate": "Fri, 23 May 2025 13:00:00 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "The Download: meet Cathy Tie, and Anthropic’s new AI models",
    "link": "https://www.technologyreview.com/2025/05/23/1117399/the-download-meet-cathy-tie-and-anthropics-new-ai-models/",
    "pubDate": "Fri, 23 May 2025 12:10:00 +0000",
    "source": "MIT Technology Review"
  },
  {
    "title": "The FDA plans to limit access to covid vaccines. Here’s why that’s not all bad.",
    "link": "https://www.technologyreview.com/2025/05/23/1117329/fda-limit-access-covid-vaccines/",
    "pubDate": "Fri, 23 May 2025 09:00:00 +0000",
    "source": "MIT Technology Review"
  },
  {
    "title": "Meet Cathy Tie, Bride of “China’s Frankenstein”",
    "link": "https://www.technologyreview.com/2025/05/23/1117373/cathy-tie-he-jiankui-china-crispr-x-twitter-feed/",
    "pubDate": "Fri, 23 May 2025 09:00:00 +0000",
    "source": "MIT Technology Review"
  },
  {
    "title": "Addendum to OpenAI o3 and o4-mini system card: OpenAI o3 Operator",
    "link": "https://openai.com/index/o3-o4-mini-system-card-addendum-operator-o3",
    "pubDate": "Fri, 23 May 2025 00:00:00 GMT",
    "source": "OpenAI News"
  }
];
