// Auto-generated by update-news.ts
export type AINewsItem = {
  title: string;
  link: string;
  pubDate: string;
  source: string;
};

export const aiNews: AINewsItem[] = [
  {
    "title": "Our latest scams survey sees changing online security habits",
    "link": "https://blog.google/technology/safety-security/google-survey-digital-security-2025/",
    "pubDate": "Wed, 04 Jun 2025 10:00:00 +0000",
    "source": "The Keyword"
  },
  {
    "title": "What’s next for AI and math",
    "link": "https://www.technologyreview.com/2025/06/04/1117753/whats-next-for-ai-and-math/",
    "pubDate": "Wed, 04 Jun 2025 08:21:24 +0000",
    "source": "MIT Technology Review"
  },
  {
    "title": "Your AI models are failing in production—Here’s how to fix model selection",
    "link": "https://venturebeat.com/ai/your-ai-models-are-failing-in-production-heres-how-to-fix-model-selection/",
    "pubDate": "Tue, 03 Jun 2025 23:47:00 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "Nvidia CEO Jensen Huang sings praises of processor in Nintendo Switch 2",
    "link": "https://venturebeat.com/gaming-business/nvidia-ceo-jensen-huang-sings-praises-of-processor-in-nintendo-switch-2/",
    "pubDate": "Tue, 03 Jun 2025 22:48:00 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "Phonely’s new AI agents hit 99% accuracy—and customers can’t tell they’re not human",
    "link": "https://venturebeat.com/ai/phonelys-new-ai-agents-hit-99-accuracy-and-customers-cant-tell-theyre-not-human/",
    "pubDate": "Tue, 03 Jun 2025 20:31:27 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "Advanced audio dialog and generation with Gemini 2.5",
    "link": "https://blog.google/technology/google-deepmind/gemini-2-5-native-audio/",
    "pubDate": "Tue, 03 Jun 2025 16:00:00 +0000",
    "source": "The Keyword"
  },
  {
    "title": "NotebookLM is adding a new way to share your own notebooks publicly.",
    "link": "https://blog.google/technology/google-labs/notebooklm-public-notebooks/",
    "pubDate": "Tue, 03 Jun 2025 16:00:00 +0000",
    "source": "The Keyword"
  },
  {
    "title": "Epic Games reveals The State of Unreal for 2025",
    "link": "https://venturebeat.com/games/epic-games-reveals-the-state-of-unreal-for-2025/",
    "pubDate": "Tue, 03 Jun 2025 15:30:00 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "What game companies can learn from AI analysis of 1.5M gamer conversations | Creativ Company",
    "link": "https://venturebeat.com/games/what-game-companies-can-learn-from-ai-analysis-of-1-5m-gamer-conversations-creativ-company/",
    "pubDate": "Tue, 03 Jun 2025 14:30:00 +0000",
    "source": "VentureBeat AI"
  },
  {
    "title": "YouTube receives continued MRC brand safety accreditation.",
    "link": "https://blog.google/products/ads-commerce/youtube-receives-continued-mrc-brand-safety-accreditation/",
    "pubDate": "Tue, 03 Jun 2025 13:00:00 +0000",
    "source": "The Keyword"
  }
];
