name: Update AI News

on:
  schedule:
    - cron: '0 */6 * * *' # каждые 6 часов
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: npm run news

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add src/data/aiNews.ts
          git commit -m "📰 Auto-update AI news [CI]" || echo "No changes to commit"
          git push